services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
      start_period: 5s

  airflow-init:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    command: ["bash", "-c", "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin_password"]
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      postgres:
        condition: service_healthy

  airflow:
    build:
      context: .
      dockerfile: ./airflow/Dockerfile
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./dbt/billboard_hot_100:/usr/local/airflow/dbt
      - ./dbt/profiles.yml:/home/airflow/.dbt/profiles.yml
    ports:
      - "8080:8080"  # Airflow webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: ["webserver"]